### ISSUE TITLE
Some characters in tag names don't work with the workflow script

### ISSUE THREAD

**Issue by danowar2k** [moodlehq/moodle-plugin-release#3]
I've already encountered git tags which don't seem to work with the script, e.g.

https://github.com/ewallah/moodle-availability_relativedate/issues/12#issuecomment-860779846

So far, I'd think there would be problems with all characters which are possibly allowed to use in tag names (see https://git-scm.com/docs/git-check-ref-format#_description) (e.g. + or whitespace) but which should be escaped in URLs.

Maybe you should integrate an escaping function somewhere?

**Comment by danowar2k** [comment]
Oh, I found some curl option to use: https://stackoverflow.com/a/2027690
This could urlencode the problematic stuff

**Comment by scara** [comment]
Hi @danowar2k;
wondering why you cannot use a semantic versioning schema e.g. `3.9.0`.

I understand your goal but, regardless being this a bug, I'm not completely sold to the need to use the plug-in version to specify its Moodle compat.

HTH,
Matteo

**Comment by danowar2k** [comment]
Well, if I were to release a plugin, I'd use semantic versioning. I'm using it at work. But our Moodle installation uses several third party plugins (popular ones, too) which do not use semantic versioning at all. I'd like for the barrier of entry to automate Moodle  releases on moodle.org and Github to be as low as possible, even if I'd think the version tags could be more streamlined among all plugin authors.

So I'd like for this script to be widely adopted, and the only way to do that now (as I can't talk a dozen plugin authors out of their release tag scheme) is to allow their scheme to be usable with this script :-)

**Comment by mudrd8mz** [comment]
Thank you @danowar2k for raising this.

I am just not sure if the scope and purpose of this workflow is clear. Your last comment suggest you would like to use this for 3rd party plugins? But this is 100% focusing on maintainers only who wish to update their own plugins in the Moodle Plugins directory. I can't see any use case for using this for managing someone else's plugins.

**Comment by danowar2k** [comment]
I think this confusion is due to the fact that I don't maintain plugins. I just raised this issue as soon as I saw a plugin maintainer who tried to use the workflow and had problems because of the tag names.

I'm not planning to manage anyone else's plugins, just trying to take note of potential problems that may occur with it.

**Comment by ewallah** [comment]
THX @danowar2k for raising my semantic ignorance ;-)

I'm not at all against semantic versioning, but until now never felt the urge to use it. So perhaps it would good to add a link explaining semantic versioning 

- in the readme file 
- when throwing an error if the tag is not 100% semantic

**Comment by mudrd8mz** [comment]
Many thanks @ewallah for raising this issue and suggesting the fix. I was able to reproduce various problems when using charcters like plus signs in tag names. This should be now fixed with the latest revision of the template.
