### ISSUE TITLE
github repository secrets vs environment secrets

### ISSUE THREAD

**Issue by ndunand** [moodlehq/moodle-plugin-release#4]
Hi,

Thanks for offering this option. I was just trying it out and when I read the README file, specifically this part:

>Go to your plugin's Settings > Secrets section and define two environmental variables there [...]

I thought I had to create an environment secret – which didn't work: the workflow failed. I fixed it by creating the 2 variables as `repository secret` (in the same place in Github).

I don't know if I am the only one being confused by this (I've neved user Github actions  before), but this had me stumped for a while.

**Comment by mudrd8mz** [comment]
Good point, thanks @ndunand. Let me encourage you to submit a pull request with README improvements :-)

**Comment by ndunand** [comment]
Sure thing @mudrd8mz , I've just opened #5 to address this.

**Comment by mudrd8mz** [comment]
Closing as pull #5 is now merged
