### ISSUE TITLE
GitHub release not marked as "already released as..."

### ISSUE THREAD

**Issue by ndunand** [moodlehq/moodle-plugin-release#6]
Hello,

After releasing a couple plugin versions through this GitHub workflow, I noticed a small incoherence in the Moodle plugins directory:

The versions previously released manually from Github through the Moodle Plugins Database using `Developer Zone > Add a new version > GitHub...` are marked as "already released as..." to indicate a link between a moodle.org release and a GitHub release tag. However, the release `20210621`(as shown below) is not marked as "already released as..." but it should be. The only difference is that is was released using this workflow.

<img width="770" alt="Screen Shot 2021-06-22 at 08 06 34" src="https://user-images.githubusercontent.com/762972/122872464-c57b1180-d330-11eb-9ac1-f6354bf5e3e2.png">

See https://moodle.org/plugins/atto_morefontcolors/versions for details.

**Comment by mudrd8mz** [comment]
Ah yes - good catch! The reason here is that the tag name is not submitted to the WS and so is not associated with the version in the plugins directory.

You can fix the already uploaded versions by editing them and filling the tag manually for now: Versions > Edit details > Version control information > VCS tag

**Comment by ndunand** [comment]
Thanks for the explanation. This is not really an issue for me but I noticed it as I was showing someone the details of this workflow.

**Comment by mudrd8mz** [comment]
Thanks @ndunand I still plan to fix this eventually, if possible.

**Comment by mudrd8mz** [comment]
The new version of the moodle-plugin-release.yml fixes this by correctly providing all the VCS related meta-data.
